# Generated by Django 5.1.2 on 2024-12-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_notification_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
